### ISSUE TITLE
使用HslCommunication库的license问题

### ISSUE THREAD

**Issue by mmaohq** [NewLifeX/NewLife.Melsec#1]
As far as I know, HslCommunication is a chargeable component, which is included in your project dependency. If your code is used in our commercial project, is it possible to cause licensing disputes?   I noticed you're using an MIT license, but I wanted to make sure

**Comment by nnhy** [comment]
你不必担心License问题，因为现在版本的NewLife.Melsec未依赖HSL。

这个项目开始于2022年4月，由客户定制的三菱协议驱动，该客户购买了HSL授权。
2022年10月，更多客户需要三菱协议驱动，我们写了FxLinks协议，并逐步上线使用。
2023年，FxLinks协议稳定以后，项目剥离HSL依赖，并从内部代码库放出，同步到github开源。

**Comment by mmaohq** [comment]
好的，明白了；thanks

**Comment by nnhy** [comment]
有任何问题，欢迎一起交流进步！
